#format for .properties
#spring.datasource.url = jdbc:mysql://localhost:3306/login_demo?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = 1q2w3e4r

#format for .yml
server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_demo
    username: root
    password: 1q2w3e4r
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true